
services:
  - type: web
    name: school-management-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn SMS.school_app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-management-system-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: school-management-system-db
    databaseName: school_management_system
    user: sms_user